import type { SVGProps } from 'react';
import * as Lucide from 'lucide-react';

type IconProps = SVGProps<SVGSVGElement> & { size?: number };
type Icon = (props: IconProps) => JSX.Element;

function wrap(LucideIcon: Lucide.LucideIcon): Icon {
  return function IconComponent(props: IconProps) {
    return <LucideIcon {...props} />;
  };
}

export const LayoutDashboard = wrap(Lucide.LayoutDashboard);
export const Calendar = wrap(Lucide.Calendar);
export const Clock = wrap(Lucide.Clock);
export const Store = wrap(Lucide.Store);
export const Star = wrap(Lucide.Star);
export const Plug = wrap(Lucide.Plug);
export const Bell = wrap(Lucide.Bell);
export const Check = wrap(Lucide.Check);
export const ChevronDown = wrap(Lucide.ChevronDown);
export const Globe = wrap(Lucide.Globe);
export const X = wrap(Lucide.X);
export const Plus = wrap(Lucide.Plus);
export const Minus = wrap(Lucide.Minus);
export const Tag = wrap(Lucide.Tag);
export const User = wrap(Lucide.User);
export const TrendingUp = wrap(Lucide.TrendingUp);
export const Reply = wrap(Lucide.Reply);
export const Info = wrap(Lucide.Info);
export const Eye = wrap(Lucide.Eye);
export const RefreshCw = wrap(Lucide.RefreshCw);
export const CreditCard = wrap(Lucide.CreditCard);
export const Mail = wrap(Lucide.Mail);
export const Zap = wrap(Lucide.Zap);
export const Hand = wrap(Lucide.Hand);
export const ChevronRight = wrap(Lucide.ChevronRight);
export const Sparkles = wrap(Lucide.Sparkles);
export const Link2 = wrap(Lucide.Link2);
export const Pencil = wrap(Lucide.Pencil);
export const Trash2 = wrap(Lucide.Trash2);
export const Download = wrap(Lucide.Download);
export const AlertCircle = wrap(Lucide.AlertCircle);
export const Camera = wrap(Lucide.Camera);
export const ImagePlus = wrap(Lucide.ImagePlus);
export const Upload = wrap(Lucide.Upload);
export const MapPin = wrap(Lucide.MapPin);
export const FileText = wrap(Lucide.FileText);
export const ClipboardList = wrap(Lucide.ClipboardList);
export const Lock = wrap(Lucide.Lock);
export const Send = wrap(Lucide.Send);
export const ShieldCheck = wrap(Lucide.ShieldCheck);
export const PawPrint = wrap(Lucide.PawPrint);
export const Scissors = wrap(Lucide.Scissors);
export const Stethoscope = wrap(Lucide.Stethoscope);
export const Phone = wrap(Lucide.Phone);
export const LogIn = wrap(Lucide.LogIn);
export const LogOut = wrap(Lucide.LogOut);
export const ArrowLeft = wrap(Lucide.ArrowLeft);
export const ArrowRight = wrap(Lucide.ArrowRight);
export const GraduationCap = wrap(Lucide.GraduationCap);
export const Footprints = wrap(Lucide.Footprints);
export const Menu = wrap(Lucide.Menu);
export const Search = wrap(Lucide.Search);
export const Ban = wrap(Lucide.Ban);
export const Play = wrap(Lucide.Play);
export const MessageSquare = wrap(Lucide.MessageSquare);
export const MessageSquareWarning = wrap(Lucide.MessageSquareWarning);
export const Megaphone = wrap(Lucide.Megaphone);
export const Gift = wrap(Lucide.Gift);
export const SlidersHorizontal = wrap(Lucide.SlidersHorizontal);
export const BarChart3 = wrap(Lucide.BarChart3);
export const Users = wrap(Lucide.Users);
export const Activity = wrap(Lucide.Activity);
export const Percent = wrap(Lucide.Percent);
export const KeyRound = wrap(Lucide.KeyRound);
export const Database = wrap(Lucide.Database);
export const AlertTriangle = wrap(Lucide.AlertTriangle);
export const FileCheck = wrap(Lucide.FileCheck);
export const UserCog = wrap(Lucide.UserCog);
export const EyeOff = wrap(Lucide.EyeOff);
export const BadgeCheck = wrap(Lucide.BadgeCheck);
export const Building2 = wrap(Lucide.Building2);
export const Wallet = wrap(Lucide.Wallet);
export const Syringe = wrap(Lucide.Syringe);
export const Heart = wrap(Lucide.Heart);
export const Receipt = wrap(Lucide.Receipt);
export const Scale = wrap(Lucide.Scale);
export const Cat = wrap(Lucide.Cat);
export const Dog = wrap(Lucide.Dog);
